<?php
/**
 * @var $block AuthorizationLink
 * @var $escaper Escaper
 */

use Magento\Framework\Escaper;
use WMZ\ForceLogin\Block\Account\AuthorizationLink;

$escaper = $block->getEscaper();

$dataPostParam = '';
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<li class="authorization-link" data-label="<?= ($block->isEnableRegister() &&
    $block->isEnable()) ? '' : $escaper->escapeHtml(__('or')) ?>">
    <a <?= /* @noEscape */$block->getLinkAttributes() ?>
        <?= /* @noEscape */
    $dataPostParam ?>>
        <?= $escaper->escapeHtml($block->getLabel()) ?>
    </a>
</li>
